services:
  mongodb:
    image: mongo:8.0
    container_name: mongodb
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - don_project_mongo_data:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    command: mongod --replSet rs0 --bind_ip_all
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
  
  mongo-express:
    image: mongo-express:1.0.2
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH: "false"
      ME_CONFIG_MONGODB_URL: "mongodb://mongodb:${MONGO_PORT}/${MONGO_DATABASE}?directConnection=true"
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
    depends_on:
      mongodb:
        condition: service_healthy
    restart: unless-stopped
  
  neo4j:
    image: neo4j:5.26
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
      - NEO4J_dbms_security_auth__enabled=true
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - don_project_neo4j_data:/data
      - don_project_neo4j_logs:/logs

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.1 
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
      - http.cors.allow-headers=X-Requested-With,Content-Type,Content-Length,Authorization
    volumes:
      - don_project_es_data:/usr/share/elasticsearch/data

  elasticvue:
    image: cars10/elasticvue:1.15.0
    container_name: elasticvue
    ports:
      - "9201:8080"
    depends_on:
      - elasticsearch
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      # KRaft Configuration
      # in kraft mode, each node requires a unique integer ID
      KAFKA_NODE_ID: 1 
      # Defines the security protocol for each custom network listener name
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      # Tells Kafka how many copies of the internal __consumer_offsets topic to keep. The default for production clusters is 3, but for a local single-node setup, it must be set to 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # Sets the minimum number of In-Sync Replicas (ISR) required to write to the internal transaction state log. Set to 1 so local transactions pass on a single broker.
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      # Tells Kafka how many copies of the internal transaction log to maintain. Set to 1 for single-node developmen
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      # Tells this instance to act as both a Broker and a controller (replacing zookeepers job)
      KAFKA_PROCESS_ROLES: 'broker,controller'
      # This environment variable tells Kafka which nodes are allowed to vote in the controller consensus group and where to reach them
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      # The public metadata addresses Kafka gives to clients (Spring Boot, AKHQ) during their initial handshake, telling them where to send future data requests.
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      # Tells Kafka to bind and listen on three distinct open ports inside the container.
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      # Tells kafka which listner name to use for broker-to-broker communication (data replication and cluster health checks)
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      # Tells Kafka which listener name is reserved exclusively for KRaft controller consensus and metadata traffic.
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      # The physical directory inside the container where Kafka stores KRaft metadata state alongside topic message logs
      KAFKA_LOG_DIRS: '/var/lib/kafka/data'
      # Cluster ID that i generated using -> docker run --rm confluentinc/cp-kafka:7.5.0 kafka-storage random-uuid
      CLUSTER_ID: 'pZxsELITTFWNmxvzXlwspw'
    volumes:
    - don_project_kafka_data:/var/lib/kafka/data
    
  akhq:
    image: tchiotludo/akhq:0.25.0
    container_name: akhq
    ports:
      - "9080:8080"
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            local-kafka:
              properties:
                bootstrap.servers: "kafka:29092"
    depends_on:
      - kafka
    restart: unless-stopped

  redis:
    image: redis:7.4
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    volumes:
      - don_project_redis_data:/data

volumes:
  don_project_mongo_data:
  don_project_neo4j_data:
  don_project_neo4j_logs:
  don_project_es_data:
  don_project_redis_data:
  don_project_kafka_data: