spring.application.name=don5

spring.data.mongodb.uri=mongodb://localhost:27017/don_project?replicaSet=rs0

# Neo4j
spring.neo4j.uri=bolt://localhost:7687
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=${NEO4J_PASSWORD:password}

# Elasticsearch
spring.elasticsearch.uris=http://localhost:9200
spring.data.elasticsearch.repositories.enabled=true


# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=don5-consumer
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Server
server.port=8080

# Scheduling
spring.task.scheduling.pool.size=5

# JPA
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

# Redis cache
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis
