spring.application.name=don5

# MongoDb
spring.mongodb.uri=mongodb://admin:supersecret@localhost:27017/don5?authSource=admin

#Neo4J
spring.neo4j.uri=bolt://localhost:7687
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=supersecret

# Redis
spring.redis.host=localhost
spring.redis.port=6379

# Elasticsearch
spring.elasticsearch.uris=http://localhost:9200
spring.elasticsearch.socket-timeout=5s

server.port=8080

